name: Deploy

on:
  push:
    branches: [ main ]

jobs:
    build:
     runs-on: ubuntu-latest
     name: Deploying to surge
     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Install node version 16
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install npm packages
      - name: Install packages
        run: npm install

      # Build react app
      - name: Build the app
        run: npm run build

      # Install Surge 
      - name: Install Surge
        run: npm install -g surge

      # Deploy to the defined URL using the token
      - name: Deploy to surge
        run: surge ./build reactbymousa.surge.sh --token ${{secrets.TOKEN}}
